PubkeyAuthentication yes
AuthenticationMethods publickey
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no

AllowAgentForwarding no
AllowTcpForwarding remote
GatewayPorts no
X11Forwarding no
PermitTunnel no

LoginGraceTime 30
MaxAuthTries 3
MaxSessions 4
ClientAliveInterval 30
ClientAliveCountMax 3
